# Generated by Django 6.0 on 2025-12-09 01:43

import django.db.migrations
import django.db.models


class Migration(django.db.migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        django.db.migrations.CreateModel(
            name="DocumentAA",
            fields=[
                (
                    "id",
                    django.db.models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", django.db.models.CharField(max_length=100)),
                ("amount", django.db.models.IntegerField()),
                ("quantity", django.db.models.IntegerField()),
            ],
        ),
    ]
