# Generated by Django 6.0 on 2025-12-09 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaza_mkforms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentaa",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.BinaryField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name"], name="plaza_mkfor_name_5364e4_idx"
                    )
                ],
            },
        ),
    ]
