# Generated by Django 6.0 on 2025-12-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaza_mkforms", "0002_documentaa_created_at_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="logo",
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
